// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Dayjs__FormattedDateTimeController from "./dayjs/formatted_date_time_controller"
application.register("dayjs--formatted-date-time", Dayjs__FormattedDateTimeController)

import Dayjs__TimeAgoController from "./dayjs/time_ago_controller"
application.register("dayjs--time-ago", Dayjs__TimeAgoController)

import Dayjs__ToDurationController from "./dayjs/to_duration_controller"
application.register("dayjs--to-duration", Dayjs__ToDurationController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SlidesController from "./slides_controller"
application.register("slides", SlidesController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
