---
EnableDefaultLinters: true
linters:
  DeprecatedClasses:
    enabled: true
  PartialInstanceVariable:
    enabled: true
  HardCodedString:
    enabled: true
    exclude:
      - '**/app/views/devise/*'
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
