inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 12

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
