inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
