inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/migrate/*"
    - "db/*schema.rb"
    - "vendor/**/*"

inherit_mode:
  merge:
    - Exclude

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
