default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  cache:
    <<: *default
    database: storage/development_solid_cache.sqlite3
  queue:
    <<: *default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/development_solid_cable.sqlite3

test:
  primary:
    <<: *default
    database: db/test<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3
  cache:
    <<: *default
    database: storage/test_solid_cache.sqlite3
  queue:
    <<: *default
    database: storage/test_solid_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/test_solid_cable.sqlite3

production:
  primary:
    <<: *default
    database: <%= File.join(ENV.fetch("DB_PATH", "storage"), "production.sqlite3") %>
  cache:
    <<: *default
    database: <%= File.join(ENV.fetch("DB_PATH", "storage"), "production_solid_cache.sqlite3") %>
  queue:
    <<: *default
    database: <%= File.join(ENV.fetch("DB_PATH", "storage"), "production_solid_queue.sqlite3") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= File.join(ENV.fetch("DB_PATH", "storage"), "production_solid_cable.sqlite3") %>
