default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: storage/development_cable.sqlite3
  migrations_paths: db/cable_migrate
  idle_timeout: 0

development:
  <<: *default

test:
  <<: *default
  database: storage/test.sqlite3

preview:
  <<: *default
  database: storage/preview.sqlite3

production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
