test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: S3
  endpoint: <%= ENV.fetch('CLOUDFLARE_ENDPOINT', nil) %>
  access_key_id: <%= ENV.fetch('CLOUDFLARE_ACCESS_KEY_ID', nil) %>
  secret_access_key: <%= ENV.fetch('CLOUDFLARE_SECRET_ACCESS_KEY', nil) %>
  region: auto
  bucket: learnertodriver-<%= Rails.env %>
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_required"
