name: tests

on: [push]

jobs:
  test:
    name: Minitest
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true

      - name: Install libvips (for image processing)
        run: sudo apt-get install -y libvips

      - name: Set up database
        run: bin/rails db:create db:schema:load

      - name: Run tests
        run: bin/rails test
