name: tests
on: [push]
jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: sudo apt-get install -y libvips
      - run: bin/rails db:create db:schema:load
      - uses: xhyrom/setup-bun@v0.1.8
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: bun install

      - run: bin/rspec
      - name: Archive logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: rails-logs
          path: ${{ github.workspace }}/log/
          retention-days: 4
